version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      - dependency-name: "*"
        dependency-type: development
    commit-message:
      prefix: "[dev]"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "*"
        dependency-type: production
    commit-message:
      prefix: "[prod]"
      include: "scope"
