repos:
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v2.3.8
    hooks:
      - id: creosote
        args:
          - --venv=.venv
          - --paths=src
          - --deps-file=pyproject.toml
          - --sections=project.dependencies
