name: Bug Report
description: File a bug report
# title: "[Bug]: "
labels: ["bug", "triage"]
# assignees:
#   - fredrikaverpil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report and help improve Creosote!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: |
        I expected Creosote to do this, but it did that instead.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      placeholder: |
        1. Do this
        2. Do that
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste the log output (make sure to use `--verbose`). This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
