name: Feature request
description: File a feature request
# title: "[Feature request]: "
labels: ["enhancement"]
# assignees:
#   - fredrikaverpil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time suggest improvements to Creosote!

  - type: textarea
    id: feature-request
    attributes:
      label: What feature request would you like to suggest?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Will this require breaking backwards compatibility?
      description: |
        If you are suggesting a change that will break backwards compatibility, please
        explain why you think it's necessary.
      options:
        - label: Yes
          required: false
        - label: No
          required: false
        - label: "I don't know"
          required: false
