name: poetry

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: fredrikaverpil/setup-pipx@v1.5
      - run: pipx install poetry
      - uses: fredrikaverpil/poetry-update@v1.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          branch: poetry-update
          commit-message: "Update poetry dependencies"
          title: "Update poetry dependencies"
          body: |

            ### Outdated dependencies:

            ```bash
            ${{ env.POETRY_OUTDATED }}
            ```

            _Note: there may be dependencies in the table above which were not updated as part of this PR.
            The reason is they require manual updating._
