name: poetry

# this workflow is only for manual / testing to ease the pain when trying to identify
# the outdated dependencies, and how production vs developer dependencies are affected.


on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "master" # temporary, until "experimental.system-git-client" configuration option is out of beta

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: fredrikaverpil/setup-pipx@v1.5

      # temporary, until required feature "--only" is out of beta
      - run: pipx install git+https://github.com/python-poetry/poetry.git@${{ env.POETRY_VERSION }}
      - run: poetry --version

      - uses: fredrikaverpil/poetry-update@v1.2
#         with:
#           show_outdated_command: "poetry show --outdated --only dev"
#           update_command: "poetry update --only dev"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: poetry-update
          add-paths: |
            poetry.lock
          commit-message: "Update developer dependencies"
          title: "Update developer dependencies"
          body: |

            :warning: There is a risk that some production dependencies which are sub-dependencies of developer dependencies can be updated by this action. Always review `poetry.lock` carefully.

            ### Updated dependencies:

            ```bash
            ${{ env.POETRY_UPDATED }}
            ```

            ### Outdated dependencies _before_ PR:

            ```bash
            ${{ env.POETRY_OUTDATED_BEFORE }}
            ```

            ### Outdated dependencies _after_ PR:

            ```bash
            ${{ env.POETRY_OUTDATED_AFTER }}
            ```

            :pencil2: There may be dependencies in the table above which were not updated as part of this PR. The reason is they require manual updating due to the way they are pinned._
