name: publish

on:
  release:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        run: poetry build

      - name: Publish package
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
