name: publish

on:
  release:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: cpython_setup
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install poetry --python '${{ steps.cpython_setup.outputs.python-path }}'

      - name: Build package
        run: poetry build

      - name: Publish package
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
